export const PATHS = {
  events: '/',
  dashboard: '/dashboard',
  myEvents: '/my-events',
  purchaseHistory: '/my-events/purchase-history',
  // loyalty: '/loyalty',
  notFound: '/404',
  eventDetail: '/events/:id',
  eventManager: '/event-manager/:id',
  teamManagement: '/team-management',
  passwordEvent: '/events/private/:id',
  profile: '/profile',
  contactUs: '/contact-us',
  AboutUs: '/about-us',
  Term: '/term',
  CheckIn: '/check-in',
  Privacy: '/privacy',
  faqs: '/FAQ',
  RefundPolicy: '/refund-policy',
  QuickGuide: '/quick-start-guide',
  ComingSoon: '/coming-soon',
  campaigns: '/campaigns',
  leaderBoard: '/leaderboard',

  instagramCallback: '/callback/instagram',
  twitterCallback: '/callback/twitter',
  kakaoCallback: '/callback/kakao',
  googleCallback: '/callback/google',

  challengeTwitterCallback: '/challenge/callback/twitter',
  challengeTiktokCallback: '/challenge/callback/tiktok',
  challengeSpotifyCallback: '/challenge/callback/spotify',
  challengeYoutubeCallback: '/challenge/callback/youtube',
  challengeFacebookCallback: '/challenge/callback/facebook',
  challengeInstagramCallback: '/challenge/callback/instagram',
};
