const {
  VITE_MESSAGES_SIGN,
  VITE_POLYGON_CHAIN_ID,
  VITE_NETWORK_NAME,
  VITE_BLOCK_EXPLORER_URL,
  VITE_POLYGON_RPC_URL,
  VITE_POLYGON_CHAIN_ID_HEX,
  VITE_ETHERSCAN_EXPLORER_URL,
} = import.meta.env;

export {
  VITE_MESSAGES_SIGN,
  VITE_POLYGON_CHAIN_ID,
  VITE_NETWORK_NAME,
  VITE_BLOCK_EXPLORER_URL,
  VITE_POLYGON_RPC_URL,
  VITE_POLYGON_CHAIN_ID_HEX,
  VITE_ETHERSCAN_EXPLORER_URL,
};
